name: Node.js CI

on:
  push:
    branches: "*"
  pull_request:
    branches: ["main"]
env:
  REACT_APP_MAIL: ${{ secrets.REACT_APP_MAIL }}
  REACT_APP_LINKEDIN_LINK: ${{ secrets.REACT_APP_LINKEDIN_LINK }}
  REACT_APP_GITHUB_LINK: ${{ secrets.REACT_APP_GITHUB_LINK }}
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: echo "My existing secret key is ${{ secrets.REACT_APP_MAIL }}"
      - run: npm install --legacy-peer-deps --force
      - run: npm run build --if-present

      - name: Deploy with gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
